import StoreLastMainRouteInLocalStorage from "@/components/StoreLastMainRouteInLocalStorage";
import { cn } from "@/lib/utils";
import { Jost } from "next/font/google";
import "./globals.css";

const jost = Jost({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          jost.className,
          "bg-lighter-grey text-xs text-blue-grey tablet:overflow-y-scroll"
        )}
      >
        <div className="max-w-[1110px] tablet:mx-10 tablet:my-12 tablet:text-md desktop:mx-auto desktop:px-12 ">
          {children}
        </div>
      </body>
      <StoreLastMainRouteInLocalStorage />
    </html>
  );
}
