import { cn } from '@/lib/utils'
import './globals.css'
import { Jost } from 'next/font/google'

const jost = Jost({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(jost.className, "bg-lighter-grey text-blue-grey text-xs tablet:text-md container mt-12")}>{children}</body>
    </html>
  )
}
