import { cn } from "@/lib/utils";
import "./globals.css";
import { Jost } from "next/font/google";

const jost = Jost({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          jost.className,
          "max-w-[1110px] bg-lighter-grey text-xs text-blue-grey tablet:mx-10 tablet:mt-12 tablet:text-md desktop:mx-auto"
        )}
      >
        {children}
      </body>
    </html>
  );
}
